spring:
  datasource:
    url: ${JDBC_DATABASE_URL}

  jpa:
    hibernate:
      ddl-auto: validate

data:
  retrieval:
    schedule: 0 0 * * * *

corona:
  datapoint:
    one: https://www.mohfw.gov.in/
    two: https://www.worldometers.info/coronavirus/
    three: https://pomber.github.io/covid19/timeseries.json

api:
  timeout: 10000
  maxattempts: 2

springdoc:
  swagger-ui:
    path: /docs

logging:
  level:
    com:
      chaitu:
        dashboard:
          carona: INFO